#Capture order Rack
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dev
  name: captureorderack
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: captureorderack
        app: captureorderack
    spec:
      containers:
      - name: captureorderack
        image: shanepeckham/captureorderack:v3
        ports:
          - containerPort: 8080
        env:
          - name: TEAMNAME
            value: "team5"
          - name: MONGOHOST
            value: "mongodb://mongodb-mongodb.dev:27017"
          - name: RABBITMQHOST
            value: "amqp://rabbit:rabbit@rabbitmq-rabbitmq.dev:5672"
---
