apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dev
  name: fulfillorderack
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: fulfillorderack
        app: fulfillorderack
    spec:
      containers:
      - name: fulfillorderack
        image: shanepeckham/fulfillorderack:v3
        ports:
          - containerPort: 8080
        env:
          - name: TEAMNAME
            value: "team5"
          - name: MONGOHOST
            value: "mongodb://mongodb-mongodb.dev:27017"
        volumeMounts:
          - mountPath: "/orders"
            name: orders
      volumes:
        - name: orders
          persistentVolumeClaim:
            claimName: fulfillpersistentvolume
