apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dev
  name: rabbitmqlistenerack
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: rabbitmqlistenerack
        app: rabbitmqlistenerack
    spec:
      containers:
      - name: rabbitmqlistenerack
        image: shanepeckham/rabbitmqlistenerack:v3
        ports:
          - containerPort: 8080
        env:
          - name: TEAMNAME
            value: "team5"
          - name: PROCESSENDPOINT
            value: "http://fulfillorderack.dev:8080/v1/order/"
          - name: RABBITMQHOST
            value: "amqp://rabbit:rabbit@rabbitmq-rabbitmq.dev:5672"
  