#Capture order Rack
kind: Service
apiVersion: v1
metadata:
  namespace: dev
  name: fulfillorderack
  labels:
    app: fulfillorderack
spec:
  selector:
    run: fulfillorderack
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080